# AWS Windows group vars
ansible_shell_type: powershell

ansible_user: "{{ lookup('ansible.builtin.env', 'DOMAIN_ADMIN_USER') }}"
ansible_password: "{{ lookup('ansible.builtin.env', 'DOMAIN_ADMIN_PASSWORD') }}"
ansible_connection: psrp
ansible_port: 5985
