# Azure Windows group vars
ansible_shell_type: powershell
# ansible_winrm_transport: ntlm
ansible_user: "{{ lookup('ansible.builtin.env', 'LOCAL_ADMIN_USER') }}"
ansible_password: "{{ lookup('ansible.builtin.env', 'LOCAL_ADMIN_PASSWORD') }}"
ansible_connection: psrp
ansible_port: 5985
ansible_psrp_proxy: socks5://localhost:12345
