ansible_user: azureuser
# ansible_ssh_private_key_file: "~/.ssh/lyas_id_rsa"
# ansible_ssh_private_key_file: '{{ hostvars["ansible01"]["ansible_ssh_private_key_file"] }}'
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -W %h:%p
  -q azureuser@20.114.208.150"
