---
- name: Issue certificate
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Issue certificate
      vars:
        sans:
          - DNS:prometheus
        key_usage:
          - digitalSignature
        key_usage_critical: true
        extended_key_usage:
          - clientAuth
        not_after: +3650d
      block:
        - name: Issue certificate
          ansible.builtin.include_role:
            name: certificate_authority
            tasks_from: issue_certificate.yml

    - name: Show certificate and key
      ansible.builtin.debug:
        msg:
          - "{{ leaf.certificate }}"
          - "{{ leaf_key.privatekey }}"
      delegate_to: localhost
