---
- name: Install Microsoft SQL
  hosts: all
  vars:
    sql_admin: 'sqladmin'
    sql_admin_password: 'SQL@dmin123!'
    sqladmin_group: 'Epic SQL Admins'
    domain_name: 'sapphire'
    domain_admin: 'admin'
    domain_admin_password: 'Loc@lPassw0rd'
    domain_controller: 'sapphire.dev'
  tasks:
    - name: Check for ActiveDirectory Powershell Module
      ansible.windows.win_feature:
        name: "RSAT-AD-PowerShell"
        state: present
    - name: Create group
      microsoft.ad.group:
        name: "{{ sqladmin_group }}"
        scope: global
        category: security
        path: ou=Users,ou=sapphire,dc=sapphire,dc=dev
        domain_username: "{{ domain_name }}\\{{ domain_admin }}"
        domain_password: "{{ domain_admin_password }}"
        domain_server: "{{ domain_controller }}"
        state: present
    - name: Create AD User
      microsoft.ad.user:
        name: "{{ sql_admin }}"
        password: "{{ sql_admin_password }}"
        update_password: on_create
        state: present
        domain_username: "{{ domain_name }}\\{{ domain_admin }}"
        domain_password: "{{ domain_admin_password }}"
        domain_server: "{{ domain_controller }}"
        path: ou=Users,ou=sapphire,dc=sapphire,dc=dev
        groups:
          add:
            - "{{ sqladmin_group }}"
        description: "SQL Admin Account"
