---
- name: Install Kuiper
  hosts: all
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        create_home: "{{ item.create_home }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
        append: "{{ item.append }}"
      loop: "{{ users }}"
    - name: Set authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_public_key }}"
      loop: "{{ users }}"
    - name: Allow users to sudo without password
      ansible.builtin.template:
        src: sudoers.j2
        dest: /etc/sudoers.d/{{ item.name }}
        owner: root
        group: root
        mode: "0400"
      loop: "{{ users }}"
