---
  - name: Playbook to configure network
    hosts: all
    become: yes
    vars:
      network_state:
        dns-resolver:
          config:
            search:
              - lcmchealth.org
    roles:
      - linux-system-roles.network
