---
- name: Get route info
  hosts: all
  vars:
  tasks:
    - name: Install ansible and other dependencies
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        # - ansible-core
        - git
        - rhel-system-roles
        - python3-pip
        - gcc
        - python3-devel
        - krb5-devel
        - krb5-libs
        - krb5-workstation
        - vim
      become: true
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        create_home: "{{ item.create_home }}"
        shell: "{{ item.shell }}"
        # groups: "{{ item.groups }}"
        # append: "{{ item.append }}"
      loop: "{{ users }}"
      become: true
    - name: Set authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_public_key }}"
      loop: "{{ users }}"
      become: true
    - name: Allow users to sudo without password
      ansible.builtin.template:
        src: sudoers.j2
        dest: /etc/sudoers.d/{{ item.name }}
        owner: root
        group: root
        mode: "0400"
      loop: "{{ users }}"
      become: true
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Sapphire-Health/ansible-aws-epic.git'
        dest: "/home/{{ item.name }}/source/ansible-aws-epic"
        version: 'master'  # Specify the branch or commit
      become: true
      become_user: "{{ item.name }}"
      loop: "{{ users }}"
