---
- name: Playbook to configure network
  hosts: all
  become: true
  vars:
    network_state:
      dns-resolver:
        config:
          search:
            - "{{ lookup('ansible.builtin.env', 'DOMAIN_NAME', default=domain_name) | lower }}"
  roles:
    - linux-system-roles.network
