---
- name: Logoff disconnected sessions
  hosts: all
  tasks:
    - name: Get a list of user sessions
      ansible.windows.win_shell: quser
      changed_when: false
      register: quser_result

    - name: Create array of disconnected sessions
      ansible.builtin.set_fact:
        disconnected_sessions: "{{ disconnected_sessions | default([]) + item | regex_search('^.*\\s(\\d+)\\s.*Disc.*', '\\1') }}"
      loop: "{{ quser_result.stdout_lines }}"
      when: item is search('Disc')

    - name: Handle disconnected sessions
      when: disconnected_sessions is defined and disconnected_sessions | length > 0
      block:
        - name: Show disconnected sessions
          ansible.builtin.debug:
            msg: "Disconnected sessions: {{ disconnected_sessions }}"

        - name: Force logoff of disconnected sessions
          ansible.windows.win_shell: logoff {{ item }}
          loop: "{{ disconnected_sessions }}"
