---
- name: Set time zone on Windows servers
  hosts: all

  tasks:
    - name: Set time zone
      community.windows.win_timezone:
        timezone: "{{ lookup('ansible.builtin.env', 'TIMEZONE', default='Mountain Standard Time') }}"
