---
- name: Join computer to domain and place in appropriate OU
  hosts: windows

  vars:
    domain_name: "sapphire.dev"
    domain_user: "{{ lookup('ansible.builtin.env', 'DOMAIN_ADMIN_USER', default=domain_admin_user) }}"
    domain_password: "{{ lookup('ansible.builtin.env', 'DOMAIN_ADMIN_PASSWORD', default=domain_admin_password) }}"

    # Mapping of types (from hostname) to OU paths
    ou_map:
      nonprod: "OU=NON-PRD,OU=EpicAZURE,OU=Servers,OU=BZN,DC=corp,DC=example,DC=com"
      prod: "OU=PRD,OU=EpicAZURE,OU=Servers,OU=BZN,DC=corp,DC=example,DC=com"
      altprod: "OU=PRD,OU=EpicAZURE,OU=Servers,OU=BZN,DC=corp,DC=example,DC=com"
      default: "OU=New Computers,DC=corp,DC=example,DC=com"

  tasks:

    - name: Extract environment from hostname
      ansible.builtin.set_fact:
        machine_type: "{{ ansible_hostname.split('-')[0] | lower }}"

    - name: Set target OU based on machine type
      ansible.builtin.set_fact:
        target_ou: "{{ ou_map.get(machine_type, ou_map.default) }}"

    - name: Debug OU for confirmation
      ansible.builtin.debug:
        msg: "Joining {{ ansible_hostname }} (type: {{ machine_type }}) to OU: {{ target_ou }}"

    # Disable AllSigned code execution?

    - name: Join the domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_user }}"
        domain_admin_password: "{{ domain_password }}"
        ou_path: "{{ target_ou }}"
        state: domain
        reboot: true

    # TODO: Diable AllSigned code execution?
