user_sqlengine: sapphire\admin
user_sqlagent: sapphire\admin
caboodle_user_warehouse: sapphire\admin
clarity_user_console: sapphire\admin
clarity_user_datalink: sapphire\admin
caboodle_user_execution_service: sapphire\admin
caboodle_install_user: sapphire\admin
slicerdicer_user: sapphire\admin


volumes:
  clarsql00:
    DriveLetter: S
    FSLabel: Clarity_SQL
  clarmount00:
    DriveLetter: M
    AllocationUnitSize: 65536
    FSLabel: null
  clarrpt00:
    AccessPath: M:\Clarity_Report1
    FSLabel: Clarity_Report1
    AllocationUnitSize: 65536
  clarrpt01:
    AccessPath: M:\Clarity_Report2
    FSLabel: Clarity_Report2
    AllocationUnitSize: 65536
  clarrpt02:
    AccessPath: M:\Clarity_Report3
    FSLabel: Clarity_Report3
    AllocationUnitSize: 65536
  clarrpt03:
    AccessPath: M:\Clarity_Report4
    FSLabel: Clarity_Report4
    AllocationUnitSize: 65536
  clarrpt04:
    AccessPath: M:\Clarity_Report5
    FSLabel: Clarity_Report5
    AllocationUnitSize: 65536
  clarrpt05:
    AccessPath: M:\Clarity_Report6
    FSLabel: Clarity_Report6
    AllocationUnitSize: 65536
  clarrpt06:
    AccessPath: M:\Clarity_Report7
    FSLabel: Clarity_Report7
    AllocationUnitSize: 65536
  clarrpt07:
    AccessPath: M:\Clarity_Report8
    FSLabel: Clarity_Report8
    AllocationUnitSize: 65536
  clarlog00:
    AccessPath: M:\Clarity_ReportLog
    FSLabel: Clarity_ReportLog
    AllocationUnitSize: 65536
  clarstg00:
    AccessPath: M:\Clarity_Stage1
    FSLabel: Clarity_Stage1
    AllocationUnitSize: 65536
  clarstg01:
    AccessPath: M:\Clarity_Stage2
    FSLabel: Clarity_Stage2
    AllocationUnitSize: 65536
  clarlog01:
    AccessPath: M:\Clarity_StageLog
    FSLabel: Clarity_StageLog
    AllocationUnitSize: 65536
  claraudit00:
    DriveLetter: F
    FSLabel: Clarity_Audit
    AllocationUnitSize: 65536

sql_install_source_dir: https://sapphirefilerepo.blob.core.windows.net/public
sql_install_iso: SW_DVD9_SQL_Svr_Enterprise_Edtn_2022_64Bit_English_MLF_X23-28423.ISO
dsc_sqltempdbdir: 'S:\SQL\SQLData'
dsc_sqltempdblogdir: 'S:\SQL\SQLData'
dsc_installsqldatadir: 'S:\SQL\SQLinstall'
dsc_instancename: MSSQLSERVER
dsc_sqlbackupdir: 'S:\SQL\'
dsc_sqluserdbdir: 'S:\SQL\SQLData'
dsc_sqluserdblogdir: 'S:\SQL\SQLLogs'
dsc_sqlsysadminaccounts: # The SQL setup requires at least one system administrator account
  - sapphire\admin
  # - .\ssm-user
# dsc_features: SQL
smss_install_source_dir: https://download.microsoft.com/download/9/b/e/9bee9f00-2ee2-429a-9462-c9bc1ce14c28
smss_install_file: SSMS-Setup-ENU.exe
ssms_product_id: "{98566bce-3110-4bc9-b372-a014a6eb5b58}"
# sql_sa_password: # can be defined as env var SQL_SA_PASSWORD=''
dsc_agtsvcaccount: sapphire\admin
dsc_sqlsvcaccount: sapphire\admin

# use these for clarity
Traceflags:
  - 2467 
  - 4139 
  - 8086 
  - 8121 
  - 12502

# use these for caboodle
#Traceflags:
#  - 2467 
#  - 4139 
#  - 8086 
#  - 8121 
#  - 12502
#  - 11064
#  - 11068
#  - 11631
#  - 11634

# Create Databases
sql_databases:
  - name: 'Clarity_PRD'
    db_size: 1024 MB
    db_max_size: 4096 MB
    db_growth: 256 MB
    log_size: 512 MB
    log_max_size: 2048 MB
    log_growth: 128 MB
    # collation: 'SQL_Latin1_General_CP1_CI_AS'
    recovery_model: 'SIMPLE'
    # log_path: 'H:\LOG'
    # data_path: 'G:\DATA'
    roles:
      - name: db_owner
        members:
          - sapphire\epicadmin # required while running the Kuiper install for SQL test to succeed
          - sapphire\kuiper-gmsa$
      - name: db_ddladmin
        members:
          - sapphire\kuiper-gmsa$
      - name: db_datawriter
        members:
          - sapphire\kuiper-gmsa$
      - name: db_datareader
        members:
          - sapphire\kuiper-gmsa$
    users:
      - sapphire\epicadmin # required while running the Kuiper install for SQL test to succeed
      - sapphire\kuiper-gmsa$
  - name: 'SystemPulse'
    db_size: 4096 MB
    db_max_size: 10240 MB
    db_growth: 256 MB
    log_size: 1024 MB
    log_max_size: 10240 MB
    log_growth: 500 MB
    # collation: 'SQL_Latin1_General_CP1_CI_AS'
    # recovery_model: 'FULL'
    # log_path: 'H:\LOG'
    # data_path: 'G:\DATA'
    roles:
      - name: db_owner
        members:
          - spadmin
      - name: db_datawriter
        members:
          - spuser
      - name: db_datareader
        members:
          - spuser
      - name: sp_user
        members:
          - spuser
    users:
      # - sapphire\epicadmin
      - spadmin
      - spuser

# Local SQL accounts
# SPAdmin
# SPUser