volumes:
  disk1:
    DriveLetter: G
  disk2:
    DriveLetter: H

sql_install_source_dir: https://sapphirefilerepo.blob.core.windows.net/public
sql_install_iso: SW_DVD9_SQL_Svr_Enterprise_Edtn_2022_64Bit_English_MLF_X23-28423.ISO
dsc_sqltempdbdir: 'H:\SQLDATA'
dsc_sqltempdblogdir: 'H:\SQLDATA'
dsc_installsqldatadir: 'G:'
dsc_sqlbackupdir: 'H:\SQL_BACKUP'
dsc_sqluserdbdir: 'G:\DATA'
dsc_sqluserdblogdir: 'H:\LOG'
dsc_sqlsyssdminaccounts:
  - sapphire\sqladmin
  - .\ssm-user
# dsc_features: SQL
smss_install_source_dir: https://download.microsoft.com/download/9/b/e/9bee9f00-2ee2-429a-9462-c9bc1ce14c28
smss_install_file: SSMS-Setup-ENU.exe
ssms_product_id: "{98566bce-3110-4bc9-b372-a014a6eb5b58}"
# dsc_sapwd: # can be defined as env var SQL_SA_PASSWORD=''

# Create SQL accounts
sql_users:
  - name: spadmin
    # password: # can be defined as env var SQL_SPADMIN_PASSWORD=''
  - name: spuser
    # password: # can be defined as env var SQL_SPUSER_PASSWORD=''

# Create Databases
sql_databases:
  - name: 'Kuiper'
    db_size: 4096 MB
    db_max_size: 10240 MB
    db_growth: 256 MB
    log_size: 1024 MB
    log_max_size: 10240 MB
    log_growth: 500 MB
    # collation: 'SQL_Latin1_General_CP1_CI_AS'
    # recovery_model: 'FULL'
    # log_path: 'H:\LOG'
    # data_path: 'G:\DATA'
    roles:
      - name: db_owner
        members:
          - sapphire\sqladmin
    users:
      - sapphire\sqladmin
  - name: 'SystemPulse'
    db_size: 4096 MB
    db_max_size: 10240 MB
    db_growth: 256 MB
    log_size: 1024 MB
    log_max_size: 10240 MB
    log_growth: 500 MB
    # collation: 'SQL_Latin1_General_CP1_CI_AS'
    # recovery_model: 'FULL'
    # log_path: 'H:\LOG'
    # data_path: 'G:\DATA'
    roles:
      - name: db_owner
        members:
          - spadmin
      - name: db_datawriter
        members:
          - spuser
      - name: db_datareader
        members:
          - spuser
      - name: sp_user
        members:
          - spuser
    users:
      # - sapphire\sqladmin
      - spadmin
      - spuser

# Local SQL accounts
# SPAdmin
# SPUser
