iris_install_source_dir: https://sapphirefilerepo.blob.core.windows.net/public
iris_install_file: IRIS-2024.1.1.347.0-lnxrh9x64.tar.gz
iris_instaserver_file: InstaServerEpicFebruary2025-139365.sh
iris_key_file: iris.key.20250213
hugepages: 2048

ssh_ca_additional_certificate_aliases:
  - epictst.sapphire.dev
  - epictst

# ou_path: OU=Computers,DC=sapphire,DC=dev

storage_safe_mode: true # set to false when resizing PVs
storage_layout:
  - name: epic_vg
    disks:
      - tstodb.epic
    volumes:
      - name: epic_lv
        size: "35g"
        fs_type: xfs
        state: present
        mount_point: "/epic"
      - name: epictmp_lv
        size: "10g"
        fs_type: xfs
        state: present
        mount_point: "/epic/tmp"
      - name: epic_core_lv
        size: "5g"
        fs_type: xfs
        state: present
        mount_point: "/epic_core"
      - name: tst_lv
        size: "20g"
        fs_type: xfs
        state: present
        mount_point: "/epic/tst"
  - name: tst_vg
    grow_to_fill: false # set to true when resizing PVs
    type: lvm
    disks:
      - tstodb.inst_tst_01
      - tstodb.inst_tst_02
      - tstodb.inst_tst_03
      - tstodb.inst_tst_04
      - tstodb.inst_tst_05
      - tstodb.inst_tst_06
      - tstodb.inst_tst_07
      - tstodb.inst_tst_08
      - tstodb.inst_tst_09
      - tstodb.inst_tst_10
      - tstodb.inst_tst_11
      - tstodb.inst_tst_12
    volumes:
      - name: tst01_lv
        size: "500g"
        raid_level: striped
        raid_stripe_size: 4M
        # verify striping and stripe sixe with this command "lvs -o+lv_layout,stripes,stripe_size"
        mount_point: "/epic/tst01"
        fs_type: xfs
        state: present
  - name: jrn_vg
    disks:
      - tstodb.nonprdfiles
    volumes:
      - name: jrn_lv
        size: "20g"
        fs_type: xfs
        state: present
        mount_point: "/epic/jrn"
      - name: epictmp_lv
        size: "60g"
        fs_type: xfs
        state: present
        mount_point: "/epicfiles/nonprdfiles"
