---
  - name: Get route info
    hosts: all
    vars:
      ansible_collections:
        - amazon.aws
        - community.aws
        - community.general
        - community.windows
        - ansible.posix
        - ansible.windows
      ansible_roles:
        - linux-system-roles.storage
    tasks:
      - name: Install ansible and other dependencies
        ansible.builtin.dnf:
          name: "{{ item }}"
          state: latest
        loop:
          - ansible-core
          - git
          - rhel-system-roles
          - python3-pip
          - gcc
          - python3-devel
          - krb5-devel
          - krb5-libs
          - krb5-workstation
          - vim
        become: true
      - name: Install pip python dependencies
        ansible.builtin.pip:
          name: "{{ item }}"
          state: present
        loop:
          - boto3
          - pywinrm
          - pykerberos
      - name: Install collections
        community.general.ansible_galaxy_install:
          type: collection
          name: "{{ item }}"
        loop: "{{ ansible_collections }}"
      - name: Install roles
        community.general.ansible_galaxy_install:
          type: role
          name: "{{ item }}"
        loop: "{{ ansible_roles }}"
      - name: Create users
        ansible.builtin.user:
          name: "{{ item.name }}"
          create_home: "{{ item.create_home }}"
          shell: "{{ item.shell }}"
          #groups: "{{ item.groups }}"
          #append: "{{ item.append }}"
        loop: "{{ users }}"
        become: true
      - name: Set authorized keys
        ansible.posix.authorized_key:
          user: "{{ item.name }}"
          state: present
          key: "{{ item.ssh_public_key }}"
        loop: "{{ users }}"
        become: true
      - name: Allow users to sudo without password
        ansible.builtin.template:
          src: sudoers.j2
          dest: /etc/sudoers.d/{{ item.name }}
          owner: root
          group: root
          mode: 0400
        loop: "{{ users }}"
        become: true
      - name: Git checkout
        ansible.builtin.git:
          repo: 'https://github.com/Sapphire-Health/ansible-aws-epic.git'
          dest: "/home/{{ item.name }}/source/ansible-aws-epic"
        become: true
        become_user: "{{ item.name }}"
        loop: "{{ users }}"